### ISSUE TITLE
Can not serve Dashboard Page

### ISSUE THREAD

**Issue by hirenrojasara** [victorcoder/dkron#146]
Getting Error after starting dkron server and accessing localhost:8080

`hiren@Hiren-PC:~/Downloads$ dkron agent -server
Starting Dkron agent...

INFO[2016-06-17T17:25:34+05:30] agent: Dkron agent starting                   node=Hiren-PC

INFO[2016-06-17T17:25:34+05:30] agent: joining: [] replay: true               node=Hiren-PC

INFO[2016-06-17T17:25:34+05:30] api: Running HTTP server                      address=:8080 node=Hiren-PC

INFO[2016-06-17T17:25:34+05:30] agent: Running for election                   node=Hiren-PC

INFO[2016-06-17T17:25:34+05:30] agent: Listen for events                      node=Hiren-PC

INFO[2016-06-17T17:25:34+05:30] agent: Cluster leadership lost                node=Hiren-PC

INFO[2016-06-17T17:25:34+05:30] agent: Cluster leadership acquired            node=Hiren-PC

2016/06/17 17:25:51 http: panic serving 127.0.0.1:15644: open templates/dashboard.html.tmpl: no such file or directory
goroutine 41 [running]:

net/http.(*conn).serve.func1(0xc8201d4160, 0x7fbfdbe412e0, 0xc8201e6028)
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1287 +0xb5

html/template.Must(0x0, 0x7fbfdbe41650, 0xc8201cccf0, 0x3)
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/html/template/template.go:330 +0x4b
`

**Comment by aromm** [comment]
@hirenrojasara Hi,  I am new to dkron but I think you need to set the `-ui-dir` configuration attribute so that Dkron knows where to look for the necessary files. Try running `dkron agent -server -ui-dir=/path/to/directory` . The directory should contain both the "static" and "templates" directories that were installed with dkron. On ubuntu I used the .deb to install and I put the following argument `-ui-dir=/usr/share/dkron` but you might have to do something different depending on your setup. Hope this helps!!

**Comment by hirenrojasara** [comment]
Thanks it worked.
