### ISSUE TITLE
Not able to access Dkron dashboard

### ISSUE THREAD

**Issue by ShirishRam** [victorcoder/dkron#162]
Hi,

I have installed dkron agent on my pet server machine following the steps given in the documentation. It had successfully installed and I was able to create and schedule jobs. But whenever I'm trying to access the dashboard using "http://IP_of_machine:8080/dashboard", it shows 'page isn't working'. I checked the log messages, it says:

http: panic serving 111.93.244.70:44209: open templates/dashboard.html.tmpl: no such file or directory

I searched for this file and I got it in this location on the machine: /usr/share/dkron/templates/dashboard.html.tmpl

Not sure why it is giving this error, what could be the possible reason for this?

Thanks,
Shirish

**Comment by victorcoder** [comment]
What OS are you running on? The .deb package includes all the necessary files in the folder `/usr/share/dkron` and the upstart script includes the parameter `ui-dir` that you need to specify in order to view the dashboard https://github.com/victorcoder/dkron/blob/master/debian/etc/init/dkron.conf#L8

I'm closing this, feel free to reopen if you're still having problems.
