### ISSUE TITLE
Disabled jobs still runs

### ISSUE THREAD

**Issue by ssenaria** [victorcoder/dkron#196]
My job definition is below. I initially wanted the job to run. Ok cool it works perfectly. Then I modified the "disabled" value to "true" and restarted dkron on the nodes. The job keeps firing during my test.

    curl -n -X POST 127.0.0.1:8080/v1/jobs \
      -H "Content-Type: application/json" \
      \
     -d '{
    "name": "cron_job2",
    "schedule": "0 * * * * *",
    "command": "/tmp/run-it.sh",
    "run_as_user": "root",
    "disabled": false,
    "tags": {
        "cluster_id": "even:1"
     }
     }'

**Comment by ssenaria** [comment]
All right so I played around with it some more. This could very well be my fault but I don't understand why this is the cause. 

So i modified the disable flag from within the Consul UI. I changed it from false->true and true->false but the changes were not honored by the servers. Now, if I make the changes via a curl command, then it work correctly. If I'm not supposed to touch the values within Consul then that's fine. I figure it was easier for me to work within the Consul UI rather than jumping back and forth between terminals.

**Comment by victorcoder** [comment]
@ssenaria I double-checked if the flag was working without any error, getting mad TBH. Glad to hear that, yes you never should edit job values outside Dkron because there's some operations that are fired when editing jobs using the API that won't get fired if you edit outside it.

Said that, what worries me about this report is that you said that **after** editing the job you restarted Dkron in all nodes. If the job `disabled` flag is `true` the job shouldn't be fired after restarting.

This is the behaviour I'm seeing in my tests.

Could you please confirm?

**Comment by ssenaria** [comment]
Correct, I restarted as a last resort when I couldn't figure out what was happening.

Good to know, all my editing is being done via APIs.

**Comment by victorcoder** [comment]
@ssenaria Could we mark this as solved?
