### ISSUE TITLE
v0.10.1 Concurrency 'forbid' not working

### ISSUE THREAD

**Issue by geoffjukes** [victorcoder/dkron#377]
Hi,

I have updated to v0.10.1, and I have seen my `"concurrency": "forbid",` tasks run concurrently:

```
$ ps aux | grep -i sch
root     41159  0.0  0.0   4504   712 ?        S    14:00   0:00 /bin/sh -c (cd /opt/io/schedule; .env/bin/python event/outgoing.py)
root     45252  0.0  0.0   4504   752 ?        S    15:00   0:00 /bin/sh -c (cd /opt/io/schedule; .env/bin/python event/outgoing.py)
```
Config:
```
{
  "name": "event-outgoing",
  "timezone": "",
  "schedule": "@hourly",
  "shell": true,
  "command": "(cd /opt/io/schedule; .env/bin/python event/outgoing.py)",
  "environment_variables": null,
  "owner": "Geoff",
  "success_count": 1012,
  "error_count": 8,
  "last_success": "2018-05-22T13:14:26.9153784-07:00",
  "last_error": "2018-05-22T09:07:48.89380791-07:00",
  "disabled": false,
  "tags": {
    "role": "io.schedule:1"
  },
  "retries": 0,
  "dependent_jobs": null,
  "parent_job": "",
  "processors": null,
  "concurrency": "forbid",
  "executor": "",
  "executor_config": null,
  "status": "running"
}
```

**Comment by victorcoder** [comment]
This is related to #349, fix and release comming today

**Comment by victorcoder** [comment]
Should be fixed in #383

**Comment by geoffjukes** [comment]
Works beautifully, thanks for the quick response @victorcoder

**Comment by victorcoder** [comment]
Hi @geoffjukes,

I think this is intentional, I tried to fix orphaned jobs that gets stalled because of "forbid".

If a job has concurrency set to `forbid` it is checked on the next run for it's actual status, and if it's not found to be running on a node, it's marked as done at the time of the next run.

Relevant code https://github.com/victorcoder/dkron/blob/046b1a8d5cb6bb65aa3565a156e33110386d613f/dkron/agent.go#L601-L639

Could you describe the sequence of events that leads to your issue?
