### ISSUE TITLE
Does Dkron provides support to store schedule in postgres or any other databases?

### ISSUE THREAD

**Issue by gm7y8** [victorcoder/dkron#504]
Use this template if you are reporting a bug. Don't use this template of you are proposing a feature.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Backend store:

**Comment by victorcoder** [comment]
No, it doesn't support storing to postgres as it is not a distributed store.

Well, key-value stores are a type of Database, and the only supported databases are distributed key-value stores.

**Comment by raghav-nayak** [comment]
Hello Dkron team,

I tried to use the DKron with K8S setup. Everything worked except persistent volume. I checked your helm project. Statefulset(sts) is used instead of deployment. This is ok but each sts pod needs separate PVC. If you scale down, the data stored a particular PVC is not accessible.

With deployment, PVC does not work properly.

With any kind of database, each deployment can share the resources. In cluster mode, leader takes all CRUD operations, there will not be any race conditions too.

Love to know what your thoughts on using any database. If DKron already supports a database as backend, let me know.

- Raghav

- Raghav
