### ISSUE TITLE
Consul - How to specify an ACL token?

### ISSUE THREAD

**Issue by greggilbert** [victorcoder/dkron#74]
(there was previously a bunch of text here; I'm throwing it out since I know the issue.)

How does one go about specifying an [ACL token](https://www.consul.io/docs/agent/http.html) to use for Consul? My whole set up is locked down via tokens, but it seems like in the current from, to get dkron to work with Consul, I'd have to add a write permission to the anonymous token. Is there a way around that?

**Comment by victorcoder** [comment]
Hi @greggilbert, thanks for testing dkron!

Dkron uses [libkv](https://github.com/docker/libkv) as an abstraction library to be able to talk to different backends. Currently libkv doesn't have support for ACLs, mainly because etcd doesn't supported ACLs until recently.

This have to change soon because libkv is using the new etc/client V3 compatible. I'm watching close the evolution of libkv and I'll add support for ACLs when it's ready.

You can follow the issue here https://github.com/docker/libkv/issues/29

**Comment by cynial** [comment]
use `export CONSUL_HTTP_TOKEN=`

**Comment by linuxmail** [comment]
hi,
sorry for asking on a closed issue: We found also Dkron (on/for Debian Stretch VMs on two datacenters with a Consul cluster of 6 nodes) as a replacement for legacy Cron and we also using Consul with a lot of ACL. Was there any changes to add the ACL Token to the configuration file ? We using a lot of services which using Consul too and to export the Consul token can be a problem, especially in a PCI DSS environment.

**Comment by egovova11** [comment]
Hi, 
it seems that valkeyrie now supports Consul Token support. Are there any plans to add it in dkron as well?

**Comment by victorcoder** [comment]
@egovova11 done in https://github.com/victorcoder/dkron/pull/508
