### ISSUE TITLE
Run job on one node at a time only?

### ISSUE THREAD

**Issue by yellow1912** [victorcoder/dkron#87]
Hello,

I have a special use case that I'm not sure how to get around it:

Every day our store has thousands of invoice to check and and send out, we usually schedule this to run at a specific time of the day. I would love to use dkron to have the advantage of ensuring that the crob job does not rely on a single machine to run, but I also have to ensure that this only runs on 1 single machine (Since we should not send invoices twice). I would love to have the ability to pick the best fit machine at run time (least resource usage for example) then run the cron there but not on any other machine.

**Comment by jaymecd** [comment]
Had same questions couple days ago - see #86

**Comment by yellow1912** [comment]
Thank you. 

I wonder if there would be a strategy to automatically choose a healthy node on run time,Specifying the tag does not guarantee the node with that tag is always suitable for running the job at the time it is called.

**Comment by victorcoder** [comment]
@yellow1912 

> I also have to ensure that this only runs on 1 single machine (Since we should not send invoices twice)

I'm putting a lot of effort to ensure Dkron works like this :smile: 

> I would love to have the ability to pick the best fit machine at run time (least resource usage for example) then run the cron there but not on any other machine.

Dkron doesn't support selecting a machine based on the used resources right now. It's probably a feature it will provide eventually in the future but it's not planned yet.

Said that, you could now use dkron (and specially from the next release >= 0.7.x) because it will provide a reliable single execution environment.

I'm closing the issue right now and write down the feature request for the future.
